# Generated by Django 3.1.3 on 2020-11-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('doctor_name', models.TextField()),
                ('admission_date', models.DateTimeField(verbose_name='Date of admission')),
            ],
        ),
    ]
