# Generated by Django 3.1.3 on 2020-11-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('pid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('weight', models.IntegerField()),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=15)),
                ('disease', models.TextField()),
                ('doctorid', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
