# Generated by Django 2.1.5 on 2020-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201125_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=5),
        ),
    ]
