# Generated by Django 2.1.5 on 2020-12-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201206_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
