# Generated by Django 2.1.5 on 2020-12-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201209_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
