# Generated by Django 2.1.5 on 2020-12-10 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201209_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='billInfo',
            fields=[
                ('bill_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('doc_charge', models.IntegerField()),
                ('med_charge', models.IntegerField()),
                ('room_charge', models.IntegerField()),
                ('surgery_charge', models.IntegerField()),
                ('no_of_days', models.IntegerField()),
                ('nursing_charge', models.IntegerField()),
                ('net_amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('doctorid', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=25)),
                ('dept', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='lab',
            fields=[
                ('labid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 12, 10, 19, 49, 1, 653273))),
                ('category', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
        migrations.CreateModel(
            name='patientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admn', models.DateTimeField(default=datetime.datetime(2020, 12, 10, 19, 49, 1, 653273))),
                ('date_of_dis', models.DateTimeField()),
                ('advance_amt', models.IntegerField()),
                ('labid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lab')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
        migrations.CreateModel(
            name='roomInfo',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roomInfo'),
        ),
        migrations.AddField(
            model_name='billinfo',
            name='labid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lab'),
        ),
        migrations.AddField(
            model_name='billinfo',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
