# Generated by Django 2.1.5 on 2020-12-10 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201210_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorid',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 20, 5, 40, 597720)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 20, 5, 40, 598759)),
        ),
    ]
