# Generated by Django 2.1.5 on 2020-12-10 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201210_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 20, 10, 33, 106180)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 20, 10, 33, 106180)),
        ),
    ]
