# Generated by Django 2.1.5 on 2020-12-14 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201210_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 19, 45, 24, 672995)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 19, 45, 24, 672995)),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='status',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('filled', 'FILLED')], max_length=15),
        ),
    ]
