# Generated by Django 2.1.5 on 2020-12-14 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201214_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 19, 51, 0, 73641)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 19, 51, 0, 74639)),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='room_type',
            field=models.CharField(choices=[('SINGLE', 'S'), ('DOUBLE', 'D'), ('SINGLE(AC)', 'S/AC'), ('DOUBLE(AC)', 'D/AC')], max_length=10),
        ),
    ]
