# Generated by Django 2.1.5 on 2020-12-14 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201214_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 19, 52, 30, 182332)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 19, 52, 30, 182332)),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='room_type',
            field=models.CharField(choices=[('S', 'SINGLE'), ('D', 'DOUBLE'), ('S/AC', 'SINGLE(AC)'), ('D/AC', 'DOUBLE(AC)')], max_length=10),
        ),
    ]
