# Generated by Django 2.1.5 on 2020-12-14 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201214_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 20, 24, 33, 311529)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 20, 24, 33, 311529)),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='room_no',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
