# Generated by Django 2.1.5 on 2020-12-21 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201221_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=5)),
                ('r_type', models.CharField(choices=[('S', 'SINGLE'), ('D', 'DOUBLE'), ('S/AC', 'SINGLE(AC)'), ('D/AC', 'DOUBLE(AC)')], max_length=10)),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 0, 14, 37, 330391)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 0, 14, 37, 330391)),
        ),
    ]
