# Generated by Django 2.1.5 on 2020-12-21 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201222_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 0, 53, 20, 370129)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 0, 53, 20, 371117)),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='room_type',
            field=models.CharField(choices=[('SINGLE', 'S'), ('D', 'DOUBLE'), ('S/AC', 'SINGLE(AC)'), ('D/AC', 'DOUBLE(AC)')], max_length=10),
        ),
    ]
