# Generated by Django 2.1.5 on 2020-12-22 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201223_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='room_no',
        ),
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 0, 29, 7, 668264)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 0, 29, 7, 669261)),
        ),
        migrations.DeleteModel(
            name='bookingDetails',
        ),
    ]
