# Generated by Django 2.1.5 on 2020-12-23 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201223_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 13, 38, 37, 303328)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='advance_amt',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 13, 38, 37, 303328)),
        ),
    ]
