# Generated by Django 2.1.5 on 2020-12-23 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201223_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='labid',
        ),
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 13, 39, 20, 635154)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 13, 39, 20, 636152)),
        ),
    ]
