# Generated by Django 2.1.5 on 2020-12-23 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201223_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 17, 48, 8, 651067)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 17, 48, 8, 651067)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='room_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.roomInfo'),
        ),
    ]
