# Generated by Django 2.1.5 on 2020-12-23 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20201223_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 20, 8, 14, 715326)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 20, 8, 14, 716323)),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
