# Generated by Django 2.1.5 on 2020-12-28 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20201223_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='room_no',
        ),
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 18, 54, 13, 431814)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 18, 54, 13, 431814)),
        ),
    ]
