# Generated by Django 2.1.5 on 2021-01-14 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20210103_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 0, 8, 30, 868306)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 0, 8, 30, 869339)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_dis',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 0, 8, 30, 869339), null=True),
        ),
    ]
