# Generated by Django 2.1.5 on 2021-01-15 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20210115_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 19, 24, 49, 778171)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 19, 24, 49, 779171)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='room_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.roomInfo'),
        ),
    ]
