# Generated by Django 2.1.5 on 2021-01-15 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20210115_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 19, 44, 36, 414755)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 19, 44, 36, 415789)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_dis',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 19, 44, 36, 415789), null=True),
        ),
    ]
