# Generated by Django 2.1.5 on 2021-01-15 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20210115_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 19, 49, 23, 713510)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_admn',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 19, 49, 23, 713510)),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='date_of_dis',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 19, 49, 23, 713510), null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='name',
            field=models.CharField(default='NONAME', max_length=20, null=True),
        ),
    ]
